### ISSUE TITLE
docker-compose example in README.md is out of date

### ISSUE THREAD

**Issue by hc-nolan** [mrgasparov/nicotine-novnc#1]
```
    image: mrgasparov/nicotine-novnc:2.0
```
Trying to use the 2.0 tag results in a manifest unknown error - looks like the proper tag is [rc-2.0.0](https://hub.docker.com/r/mrgasparov/nicotine-novnc/tags). Should probably be changed to `latest`

**Comment by mrgasparov** [comment]
Thanks for spotting that! I have just fixed it 😄
